lesson_1
DrawGun/th_react_main pull request #1
Opened 2017-05-25 21:51 UTC by DrawGun

2017-05-26 08:28 UTC, blackleadsu requested changes

2017-05-26 08:28 UTC, blackleaden commented on components/containers/BlogPage.jsx
> +  { text: "Первый немного текста", link: "https://facebook.github.io/react/img/logo.svg" },
Написано "link" а там картинка. Идеально - ключ "image" с объектом вида 
```
{ src: '...', alt: : '...', width: '...', height: '...' }
```

2017-05-26 08:28 UTC, blackleaden commented on components/ui/BlogItem.jsx
> +          alt="Это картинка" />
alt д.б. индивидуален для каждой картинки.

2017-05-26 08:28 UTC, blackleaden commented on components/ui/BlogList.jsx
> +  getPosts() {
Почему бы просто не поместить это в render?

2017-05-26 08:28 UTC, blackleaden commented on components/ui/BlogList.jsx
> +          key={key}
В качестве key лучше использовать уникальный id поста (чтобы при перерисовке react не считал элементы с разными данными одинаковыми и страница не "скакала"). Id постов поместить в исходный массив с записями.

2017-05-26 08:28 UTC, blackleaden commented on components/ui/TextEl.jsx
> +const TextEl = ({ text }) => <div>
Зачем два компонента чтобы обернуть текст в span?

2017-05-26 09:52 UTC, DrawGun commented on components/containers/BlogPage.jsx
> +  { text: "Первый немного текста", link: "https://facebook.github.io/react/img/logo.svg" },
ok, не понял задачи, поправлю, спасибо

2017-05-26 09:53 UTC, DrawGun commented on components/ui/BlogItem.jsx
> +          alt="Это картинка" />
ok,  поменяю, согласно новой новой логике с `image`

2017-05-26 09:53 UTC, DrawGun commented on components/ui/BlogList.jsx
> +  getPosts() {
так проще читается, а это принципиально?

2017-05-26 09:54 UTC, DrawGun commented on components/ui/BlogList.jsx
> +          key={key}
ok, хорошее замечание, поправлю, спасибо

2017-05-26 09:55 UTC, DrawGun commented on components/ui/TextEl.jsx
> +const TextEl = ({ text }) => <div>
насколько я понял, это надо по [заданию](http://thinknetica.teachbase.ru/course_sessions/30933/tasks/6495/take)

2017-05-27 08:40 UTC, blackleadsu requested changes

2017-05-27 08:40 UTC, blackleaden commented on components/ui/TextEl.jsx
> +const TextEl = ({ text }) => <div>
"получающий в качестве дочернего элемента строку с некоторым текстом" означает использование строки в качестве children. TextEl не требуется, достаточно 
`<TextBox>{text}</TextBox>`
прямо в BlogItem.

2017-05-27 08:40 UTC, blackleaden commented on components/ui/BlogList.jsx
> +  getPosts() {
Усложнение структуры для сокращения render на 9 строк, когда он и так небольшой и помещается в экран, неоправданно. Пока не принципиально, но когда код разрастется это будет мешать.

2017-05-27 11:37 UTC, index01d approved these changes

2017-06-05 22:04 UTC, merged