lesson_6
DrawGun/th_react_main pull request #6
Opened 2017-07-19 22:57 UTC by DrawGun

2017-07-24 09:10 UTC, index01d requested changes
Теперь можно не передавать коллбэк для лайка и количество лайков в свойствах по иерархии. Лучше создать LikeContainer, там из второго аргумента ownProps получить item.id (идентификатор записи), по ней из state (в stateToProps) получить количество лайков, а в actionsToProps подготовить коллбэк.

То есть я имею ввиду примерно следующую схему (код приведен из домашнего задания другого слушателя):

В LikeContainer реализовать redux-container:

```
import { get, find, flowRight } from 'lodash';

import Like from 'components/ui/Like';
import { addLike } from 'actions/Like';

...
const stateToProps = (state, ownProps) => ({
  amount: get(
    find(state.posts.items, { id: ownProps.itemId }), 
    'likes', 
    get(state, 'post.item.likes', 0)
  )
});

const actionsToProps = (dispatch, ownProps) => (
  addLike: () => dispatch(addLike(ownProps.itemId))
);

export default connect(stateToProps, actionsToProps)(Like);
```

Презентационный компонент станет таким

```
import React from 'react';
import Button from 'react-mdl/lib/Button';


const Likes = ({addLike, amount}) =>{

    return(
        <Button onClick={()=> addLike()}
             style={{border: '1px solid green',
             width: 'auto',
             cursor: 'pointer'}}>
            {`likes: ${amount}`}
        </Button>
    )
};


Like.propTypes = {
    amount: React.PropTypes.number.isRequired,
    addLike: React.PropTypes.func.isRequired
};

export default Like;
```

В BlogItem использовать его следующим образом

```
import LikeContainer from 'containers/LikeContainer';
...
<LikeContainer itemId={item.id} /> // здесь разумеется рендерить с условием, только когда item.id уже есть
```

2017-07-24 09:10 UTC, index01d commented on src/components/BlogPage.jsx
>    pieChartColumns() {
лучше выделить Redux'овый PieChartContainer и вынести туда эту логику

2017-07-24 09:10 UTC, index01d commented on src/components/Post.jsx
>  import { postsPath } from 'helpers/routes/posts';
этот импорт выглядит лишним, все роуты должны формироваться в контейнере, презентационному компоненту об этом знать незачем

2017-07-24 11:30 UTC, blackleadsu requested changes
Ошибка в сервере, th_react_blog_server, index.js не отдает данные без указания page и step. Что-то вроде этого спасает ситуацию:
``` 
var step = parseInt(req.query.step) || 2;
var page = (parseInt(req.query.page) || 1) - 1;
```

В остальном, рекомендую:
1) учесть комментарии Эдуарда
2) как минимум поставить заглушки, чтобы приложение не падало с ошибками при попытках воспользоваться нереализованными вещами (включая лайк, который перестал работать!)
3) круто было бы доделать доп.задания (включая лайк, инкремент которого было бы хорошо реализовать с помощью API).
P.S. в консоль падают довольно конкретные описания ошибок

2017-07-24 11:30 UTC, blackleaden commented on src/components/BlogPage.jsx
>          <Search handleSearch={ this.handleSearch } />
Ты его не передаешь, передай хотя бы заглушку, чтобы не падало с ошибкой при попытке воспользоваться поиском.

2017-07-28 11:51 UTC, blackleadsu requested changes
Обязательно: исправить ошибку + убрать лишний файл src/Pagination.jsx.
Рекомендую, если будет время: сделать поиск и пагинацию через url (c использованием history).

2017-07-28 11:51 UTC, blackleaden commented on src/App.jsx
> +  render() {
ошибка возникает здесь, из-за побочного эффекта в рендере. Следует вынести навешивание коллбэков в componentWillMount, а коллбэк -- вне компонента

2017-07-28 13:01 UTC, blackleadsu approved these changes

2017-07-28 16:56 UTC, merged